image: "akkuscm/akku"

variables:
  XDG_CACHE_HOME: "$CI_PROJECT_DIR/.cache"
  AKKU_CACHE_DIR: "$CI_PROJECT_DIR/.cache/akku"

cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - .akku/src
    - .cache/akku

stages:
  - bootstrap
  - build
  - test

# Bootstrap from Chez Scheme
bootbuild:
  stage: bootstrap
  before_script:
    - apk add --no-cache make
  script:
    - make
    - make install
  artifacts:
    paths:
      - loko

# Test self-compilation
build:
  stage: build
  before_script:
    - apk add --no-cache make
  script:
    - make .akku/env
    - LOKO_SOURCE=.akku/lib .akku/env ./loko --program compile-loko.sps
    - chmod +x loko.out
  artifacts:
    paths:
      - loko.out

test:
  stage: test
  before_script:
    - apk add --no-cache make
  script:
    - make .akku/env
    - echo '(exit 0)' | ./loko.out
    - .akku/env ./loko.out --program tests/test-fibers.sps
    - LOKO_SOURCE=.akku/lib .akku/env ./loko.out --compile tests/test-buddy.sps --output tests/test-buddy
    - tests/test-buddy
    - .akku/env ./loko.out --program tests/test-drivers-ps2-keyboard.sps
    - (cd tests/r6rs; akku install; .akku/env ../../loko.out --program run.sps)
    - cp loko.out loko
    - make install
    - (cd tests/r6rs; akku install; .akku/env ../../loko.out -feval --compile run.sps --output run.bin)
    - tests/r6rs/run.bin
    - (cd tests/r6rs; akku install; .akku/env ../../loko.out -feval --compile run-via-eval.sps --output run-via-eval.bin)
    - tests/r6rs/run-via-eval.bin

build_samples:
  stage: test
  before_script:
    - apk add --no-cache make
  script:
    - make
    - make install
    - make -j$(nproc) samples
    - samples/hello/hello
